### ISSUE TITLE
Support multiple keys per user

### ISSUE THREAD

**Issue by deric** [deric/puppet-accounts#18]
Currently a user can have only single ssh key.

**Comment by jceloria** [comment]
This maybe something already considered...
It would be also nice to have the option to manage_keys exclusively as well as append to an existing authorized_keys file. We have existing keys deployed for different users that we are not yet ready to clobber and at the same time would like to exclusively manage root's keys.

**Comment by meganuke19** [comment]
+1 on this enhancement

**Comment by deric** [comment]
This feature is not very well designed nor documented. You should be able to pass multiple keys via:

```yaml
   ssh_keys:
     key1:
      type: "ssh-rsa"
      key: "AAA..."
      comment: "first key"
     key2:
      type: "ssh-rsa"
      key: "AAA..."
      comment: "second key"
```
Instead of using `ssh_key` you have to specify a multi-level `ssh_keys` hash. This behaviour will probably change in future versions.

**Comment by marshcroft** [comment]
IS the Multiple keys still working? I am using PE 2015.3 and I get the following error 
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, can't convert Symbol into Hash at /etc/puppetlabs/code/environments/production/modules/accounts/manifests/user.pp:204:9

This is my hiera code
accounts::users:
  username:
    comment: "my comment"
    pwhash: "my hash"
    uid: 1471
    gid: 1471
    home: "/home/username"
    ssh_keys:
      key1:
      type: "ssh-rsa"
      key: "my Key"
      comment: "my comment"

**Comment by deric** [comment]
Is your indentation correct? It should be something like:
```
    ssh_keys:
      key1:
        type: "ssh-rsa"
        key: "my Key"
        comment: "my comment"
```
