### ISSUE TITLE
Supplementary group membership works only for adding

### ISSUE THREAD

**Issue by dene14** [deric/puppet-accounts#19]
For e.g. you have a user with
- groups: 
  - sudo

if you change it to:
- groups: 
  - temp

you will get:
Notice: /Stage[main]/Accounts::Users/Accounts::User[dboulas]/User[dboulas]/groups: current_value sudo, should be sudo,temp (noop)

so... no removal for sudo group. Passing an empty array also won't change membership.

**Comment by orvtech** [comment]
Having a similar issue

**Comment by deric** [comment]
Well according to the [docs](https://docs.puppetlabs.com/puppet/latest/reference/type.html#group) this seems to be a feature of Puppet:
> Manage groups. On most platforms this can only create groups. 

I guess we could solve this by using one of those:
 * [puppet-module-group](https://github.com/pdxcat/puppet-module-group)
 * [puppet-gpasswd](https://github.com/onyxpoint/puppet-gpasswd)

Probably we can resolve this together with #25.

**Comment by deric** [comment]
With current version from master you should be able to manage members from group definition:
```yaml
---
accounts::groups:
  sudo:
    members: ['dboulas', 'foo']
```

**Comment by deric** [comment]
Latest (unreleased) version changes group management, it should not matter where you define membership:
```yaml
accounts::groups:
  www-data:
    gid: 33
    members: ['apache']
  users:
    gid: 999
accounts::users:
  apache:
    comment: 'apache webserver'
  nginx:
    groups: ['www-data']
```
This should result into:

```ruby
{www-data: {gid: 33, memebers: ['apache', 'nginx']}, users:{gid: 999}}
```
