### ISSUE TITLE
 Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: The value 'comment' cannot be converted to Numeric. on node

### ISSUE THREAD

**Issue by meganuke19** [deric/puppet-accounts#26]
I use this hiera data
```
---
accounts::groups:
  admins:
    gid: 500
accounts::users:
  test:
    uid: 600
    ssh_keys:
      key1:
        type: "ssh-rsa"
        key: "AAAAB3NzaC1yc2EAAAABIwAAAQEAqP+dXMfw7XBlO9hKbPwWSGPxBi6xRNcgDtiitJ5k76xChb+NJq9zYzfOeSOTUbNmAuS8A7TcDp8mUts/+lmHaE/kqw2elo3ePNZBITj8snXomoDLxE2m7P9Nb5KQYn0P9oTnK05VOPqiXClsHiVsxBpIo0TRvcLjDd07kv/nPNP1OtioxnaQFaExu6TJ9S6iJZixBiWnvpsqoGM/UqDfoYyAlaSZPgFU5AIy7gGSVIY5fPuXWQs1qtovcwXYFojdfOyQnHUDPe/2QFkd+9dDi5jhfRxZxPZJflXpF/mP6HJ6rGC9PQLrfCRZgTsbJWRCjEnYoRvRwOEkN+mFPu6tqQ=="
    pwhash: $6$cuHSjfrU$bRB/ln5VfdYgiORTYGAU9gTU9uUbwbRUjbldNlQV98nxCPiKLmMpJCG6fcEhQPSMkyGzx4HeA9fLYg1hhvC420
    groups:
      - admins
```
but receive error in subj.
