### ISSUE TITLE
Invalid parameter comment on ssh_authorized_key

### ISSUE THREAD

**Issue by adepretis** [deric/puppet-accounts#36]
This commit seems to break the module: https://github.com/deric/puppet-accounts/commit/cc527ab3bd3700c2576c42f202e7c36059e493a8

> Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter comment on Ssh_authorized_key[xxx] on node yyy

**Comment by deric** [comment]
Which version of Puppet do you use?

**Comment by adepretis** [comment]
ah, sorry, totally forgot that information: 3.8.5 and it doesn't work with 3.8.6 neither ... the docs for 3.8, 4.0-4.3 also don't show a `comment` attribute for `ssh_authorized_key`

**Comment by deric** [comment]
Strange, [automated builds on Puppet 3.8.5](https://travis-ci.org/deric/puppet-accounts/jobs/109445926) seems to pass. Usually this type of error could be easily reproduced on Travis. We don't test against Puppet 4.x yet, but I can do that right away. 

Which distribution do you use? The original error #26 was also a bit strange. I'd like to reproduce the bug, so that we won't reappear again.

**Comment by adepretis** [comment]
Ubuntu 14.04

**Comment by deric** [comment]
Could you provide user's configuration that you use (anonymized if needed) - pretty much just which fields you set to non empty value.

**Comment by adepretis** [comment]
```
accounts::users:
  myuser:
    uid: 1000
    comment: 'My Awesome User'
    shell: '/bin/bash'
    pwhash: '$myawesomehash'
    managehome: true
    home_permissions: '0750'
    purge_ssh_keys: true
    ssh_keys:
      'myawesomefirstkey':
        type: 'ssh-rsa'
        key: 'yay'
      'myawesomesecondkey':
        type: 'ssh-rsa'
        key: 'yay'
```
