### ISSUE TITLE
users are not added to (all) groups

### ISSUE THREAD

**Issue by dmccuk** [deric/puppet-accounts#38]
Hi Tomas,
I was looking for a way contact you and this was the only one I could find. I'm having a problem getting groups assigned to the users I'm trying to add - I've installed puppet-accounts & gpasswd.

Hiera:
```yaml
accounts::groups:
  engineers:
    gid: 503
    members: ['user1', 'john']

accounts::users:
  user1:
    comment: "Linux user1"
    groups: ['engineers' ]
    shell: "/bin/bash"
    ssh_keys:
      'DM@here':
        type: "ssh-rsa"
        key: "a_valid_public_ssh_key_string"
  john:
    comment: "John Doe"
    groups: ["sudo", "users"]
    shell: "/bin/bash"
    pwhash: "$6$GDH43O5m$FaJsdjUta1wXcITgKekNGUIfrqxYogW"
    ssh_keys:
      'john@doe': # an unique indentifier of a key
        type: "ssh-rsa"
        key: "AAAAAABBBBBCCCCC"
```
----
Output on puppet run:
```
Info: Applying configuration version '1457439312'
Notice: /Stage[main]/Accounts::Groups/Accounts::Group[sudo]/Group[sudo]/ensure: created
Notice: /Stage[main]/Accounts::Groups/Accounts::Group[engineers]/Group[engineers]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[john]/Group[john]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[user1]/User[user1]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[user1]/File[/home/user1/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[user1]/File[/home/user1/.ssh/authorized_keys]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[user1]/Ssh_authorized_key[DM@here]/ensure: created
Info: FileBucket got a duplicate file {md5}d41d8cd98f00b204e9800998ecf8427e
Notice: /Stage[main]/Accounts::Users/Accounts::User[john]/User[john]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[john]/File[/home/john/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[john]/File[/home/john/.ssh/authorized_keys]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[john]/Ssh_authorized_key[john@doe]/ensure: created
Info: FileBucket got a duplicate file {md5}d41d8cd98f00b204e9800998ecf8427e
Notice: Finished catalog run in 3.60 seconds
```
```
[root@home]# groups user1
user1 : user1
[root@home]# groups john
john : john
```
Could he help me to resolve?

Regards

Dennis
