### ISSUE TITLE
Duplicate declaration: Ssh_authorized_key[user@domain] is already declared;

### ISSUE THREAD

**Issue by jordigg** [deric/puppet-accounts#40]
Got the following error on 1.2.1:
`Duplicate declaration: Ssh_authorized_key[user1@domain] is already declared;`
This happens when I try to add two SSH Keys with the same name but on different users. Hiera example here:

``` yaml
accounts::users:
  user1:
    comment: "User One"
    ssh_keys:
      user1@domain:
        type: "ssh-rsa"
        key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQC+g9RlVRmA84VPH8+UIszzH6eyRftEBk6cs0YbHRIY9amcWtv41ziCu1shFLRyYdcHpVo0YIrJj+lstpqNVE1PSISc8xYpksKkT81PWH/41YtxXn2VFtNgXGx20ziMXtHQatrs3Ul"
    groups: ['sudo', 'group1']
    shell: '/bin/bash'
  user2:
    comment: "User Two"
    ssh_keys:
      user1@domain:
        type: "ssh-rsa"
        key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQC+g9RlVRmA84VPH8+UIszzH6eyRftEBk6cs0YbHRIY9amcWtv41ziCu1shFLRyYdcHpVo0YIrJj+lstpqNVE1PSISc8xYpksKkT81PWH/41YtxXn2VFtNgXGx20ziMXtHQatrs3Ul"
    groups: ['sudo', 'group1']
    shell: '/bin/bash'
```

Works using a different name for one of the keys or by defining they one single key and adding the name of the key on the comment parameter like:

``` yaml
accounts::users:
  user1:
    comment: "User one"
    ssh_key:
      type: "ssh-rsa"
      key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQC+g9RlVRmA84VPH8+UIszzH6eyRftEBk6cs0YbHRIY9amcWtv41ziCu1shFLRyYdcHpVo0YIrJj+lstpqNVE1PSISc8xYpksKkT81PWH/41YtxXn2VFtNgXGx20ziMXtHQatrs3Ul"
    groups: ['sudo', 'group1']
    shell: '/bin/bash'
```
