### ISSUE TITLE
Manage users failed

### ISSUE THREAD

**Issue by mobilesfinks** [deric/puppet-accounts#50]
CentOS 7,  puppet-agent 3.6.2, ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

``` yaml
accounts::users:
    defaults:
      shell: /bin/bash
    manage: true
    users:
      dalp:
        uid: 1005
        comment: dalp
        groups:
        - users
      deployer:
        uid: 1010
```

```
Error: /Stage[main]/Accounts::Users/Accounts::User[dalp]/User[dalp]/ensure: change from absent to present failed: 
Could not create user dalp: 
Execution of '/usr/sbin/useradd -c dalp -g dalp -d /home/dalp -s /bin/bash -u 1005 -m dalp' 
returned 6: useradd: group 'dalp' does not exist
```

```
Error: /Stage[main]/Accounts::Users/Accounts::User[deployer]/User[deployer]/ensure: 
change from absent to present failed: 
Could not create user deployer: 
Execution of '/usr/sbin/useradd -c dalp -g deployer -d /home/deployer -s /bin/bash -u 1010 -m deployer' 
returned 6: useradd: group 'deployer' does not exist
```

**Comment by deric** [comment]
Which version of `puppet-accounts` do you use?

**Comment by mobilesfinks** [comment]
in Puppetfile i use:
mod 'deric-accounts'

last on Forge 1.3.3

**Comment by deric** [comment]
Should be fixed in latest release (v1.4.1). Could you check that, please?

**Comment by deric** [comment]
A valid configuration for the latest version would look like this:
```yaml
accounts::user_defaults:
  shell: /bin/bash
  manage_group: true
accounts::users:
  dalp:
    uid: 1005
    comment: dalp
    groups:
      - users
  deployer:
    uid: 1010
```
[A minimal script](https://gist.github.com/deric/0b6fdbd43eb7b9fe711330ee4a8f39d9) to reproduce the configuration.

Here's output on CentOS 7 (clean system):
```
[root@centos7-3 /]# puppet apply -e "class{'::accounts': }"
Notice: Compiled catalog for centos7-3.8 in environment production in 0.31 seconds
Notice: /Stage[main]/Accounts/Accounts::Group[dalp]/Group[dalp]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[dalp]/User[dalp]/ensure: created
Notice: /Stage[main]/Accounts::Groups/Accounts::Group[users]/Group[users]/members: members changed '' to 'dalp'
Notice: /Stage[main]/Accounts::Users/Accounts::User[dalp]/Accounts::Authorized_keys[dalp]/File[/home/dalp/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[dalp]/Accounts::Authorized_keys[dalp]/File[/home/dalp/.ssh/authorized_keys]/ensure: created
Notice: /Stage[main]/Accounts/Accounts::Group[deployer]/Group[deployer]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deployer]/User[deployer]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deployer]/Accounts::Authorized_keys[deployer]/File[/home/deployer/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deployer]/Accounts::Authorized_keys[deployer]/File[/home/deployer/.ssh/authorized_keys]/ensure: created
Notice: Finished catalog run in 0.44 seconds
[root@centos7-3 /]# id dalp
uid=1005(dalp) gid=1000(dalp) groups=1000(dalp),100(users)

```
