### ISSUE TITLE
Additional arguments in SSH keys

### ISSUE THREAD

**Issue by xpz25nfh** [deric/puppet-accounts#52]
Hi there, 

Is there a way you can permit a user to specify arguments that prefix the `ssh-rsa` identifier in a ssh key?  for example, in a user's `$HOME/.ssh/authorized_keys` file, I'd like to be able to put:

```
from="serverA,serverB,",command="/path/to/script.sh arg1 $SSH_ORIGINAL_COMMAND",no-port-forwarding,no-X11-forwarding,no-agent-forwarding ssh-rsa <public key>
```

It would be a free-form thing I imagine with no interpolation.  This is valid syntax...

Thanks!

**Comment by deric** [comment]
Sorry for late reply, the feature is already implemented, it just wasn't really documented. For any SSH key you can pass options as an array:

```yaml
accounts::users:
  xpz25nfh:
    ssh_keys:
      'mykey1':
        type: 'ssh-rsa'
        key: 'AAAA....'
        options:
          - 'no-port-forwarding'
          - 'no-X11-forwarding'
          - 'no-agent-forwarding'
          - 'from="serverA,serverB"'
          - 'command="/path/to/script.sh arg1 $SSH_ORIGINAL_COMMAND"'
```
Let me know if you run into any problems.
