### ISSUE TITLE
Rename `group_ensure`

### ISSUE THREAD

**Issue by deric** [deric/puppet-accounts#6]
Rename `group_ensure` parameter to simple `ensure`

https://github.com/deric/puppet-accounts/blob/master/manifests/group.pp#L5

To make the usage more straightforward:

```yaml
accounts::groups:
 www-data:
   ensure: 'absent'
accounts::users:
  foo:
   ensure: 'absent'
```
instead of (current version):
```yaml
accounts::groups:
 www-data:
   ensure_group: 'absent'
accounts::users:
  foo:
   ensure: 'absent'
```
@jbartko what do you think?
