### ISSUE TITLE
Don't add user on groups on RHEL 7 

### ISSUE THREAD

**Issue by polivox** [deric/puppet-accounts#71]
When you use yaml: 
```yaml
oracle:
    uid: 500
    comment: "Oracle User Service"
    groups: ['www-data']
    shell: "/bin/bash" 
```
The module doesn't add user Oracle to group `www-data`, but the groups is created.
