### ISSUE TITLE
Enhancement Request:  Add sudo entry

### ISSUE THREAD

**Issue by Larz98** [deric/puppet-accounts#73]
Being able to write a one liner to a sudoers.d/file named after the username  would be very helpful on EL system.    This would empower privilege escalation without needing to configure sudoers via a second module and tie it into this with groups.   

```puppet
if $sudoers!=undef and $sudoers != '' {
      file { "/etc/sudoers.d/${username}":
          content => "${username} ${sudoers}\n\n",
          mode    => 0440,
          owner   => root,
          group   => root
      }
  }

**Comment by deric** [comment]
It might not work out of the box on all distributions and it seems to me a bit like mixing functionality from other modules. Original idea was to keep this module very simple. Though I understand your motivation.

It might make sense to allow groups rules as well, something like:
```
%admins ALL=(ALL) NOPASSWD: ALL
```
So the user's configuration might look like this?:
```yaml
accounts::users:
 john:
  sudoers: 'ALL=(ALL) NOPASSWD: ALL'
accounts::groups:
 admins:
   gid: 115
   sudoers: 'ALL=(ALL) NOPASSWD: ALL'
```
Eventually we might need to handle priority of rules, thus possibility to override `/etc/sudoers.d/{user}`. In order to avoid further API chages it might be safer to use arrays from the beginning:
```yaml
accounts::users:
 john:
  sudoers: 
    - 'ALL=(ALL) NOPASSWD: ALL'
    - 'rule 2'
```
or hashes:
```yaml
accounts::users:
 john:
  sudoers: 
    10_john: 'ALL=(ALL) NOPASSWD: ALL'
    11_john: 'rule 2'
```
Maybe I'm already over-engineering this :) What do you think?
