### ISSUE TITLE
Setting `inclusive` membership on users is not possible

### ISSUE THREAD

**Issue by sigv** [deric/puppet-accounts#78]
[membership](https://docs.puppet.com/puppet/4.9/types/user.html#user-attribute-membership) can be set on a user and it can specify either that the groups listed is a minimal set or that the groups listed in an inclusive set. There does not appear to be a possibility to set that through this module and that is not great for us. Is there a reason for why that attribute cannot be set on the custom defined type?

**Comment by deric** [comment]
The way how the DSL is processed now have to create accounts first, then deal with groups and its members. It might be complicated to enforce different membership levels for each user.

Currently the membership is set [here](https://github.com/deric/puppet-accounts/blob/master/manifests/group.pp#L36). 

Though, I could try to support something like this, but it will require some refactoring.
```yaml
accounts::user_defaults:
    membership: minimal
accounts::groups:
  www-data:
    members: ['john']
accounts::users:
  john:
    groups: ["sudo", "users"]
    membership: minimal
  trudy:
    groups: ["sudo", "users"]
    membership: inclusive
```
