### ISSUE TITLE
How does groups: work? 

### ISSUE THREAD

**Issue by hzzbh3** [deric/puppet-accounts#81]
Please let me know if this statement is true: 
I would expect that this entry creates a user named john and adds john to the sudo and users groups. 

First scenario: 
```yaml
  john:
    comment: "John Doe"
    groups: ["sudo", "users"]
    shell: "/bin/bash"
    pwhash: "$6$GDH43O5m$FaJsdjUta1wXcITgKekNGUIfrqxYogW"
```

Second scenario: 

I would expect that this entry would create a group called appusers and have nasapp as a member of that group. 
```yaml
accounts::groups:
  appusers:
    members: ["nasapp"]
```
Both of these are not working and i am unsure why.
