### ISSUE TITLE
home_mode is not supported ?

### ISSUE THREAD

**Issue by durga1983** [deric/puppet-accounts#85]
I am unable to use home_mode which can set custom rwx permissions to the home directory. It gives an error " unsupported variable"

**Comment by deric** [comment]
Could you post some code example?

You're probably looking for `home_permissions` parameter
```yaml
accounts::users:
  john:
    home_permissions: '0740'
    groups: ["sudo", "users"]
    shell: "/bin/bash"
```
