### ISSUE TITLE
unwanted created groups with same gids as uids

### ISSUE THREAD

**Issue by dfrise** [deric/puppet-accounts#87]
Hi,
First thanks for the awesome module that we use since we started using hiera.

This issue appeared since we migrated from 1.5.2 to 1.5.3.
Assuming following common.yaml extract:

```
accounts::groups:
  ci:
    gid: '10010'
accounts::users:
  testci:
    uid: '1003'
    primary_group: 'ci'
    populate_home: true
```
Which means we want the **testci** user to belong to the primary group **ci**.
After running the first puppet run on a new node, the testci user gets created:

```
# grep testci /etc/group
testci:x:1003:
# id testci
uid=1003(testci) gid=1003(testci) groups=1003(testci)
```
Hopefully this does not affect already configured nodes.

Uncommenting the #141 line in user.pp seems to fix this:
```
140   User<| title == $username |> {
141     #gid       => $real_gid,
142     comment    => $comment,
143     managehome => $managehome,
144     home       => $home_dir,
145   }
```
Was this intentional (are we missing something)?
Thanks,
Dominique
