### ISSUE TITLE
Groups doesn't update 

### ISSUE THREAD

**Issue by lagerstrom** [deric/puppet-accounts#92]
When changing the hiera file and adds or removes a user from a group the change is not updated on the system. 
So changing from this

```
 # User configuration                                                                                                                        
 accounts::users:                                                                                                                            
   test:                                                                                                                                
     managehome: true                                                                                                                        
     comment: "Test user"                                                                                                         
     groups: ["sudo", "plugdev", "admins"] 
```

to this

```
 # User configuration                                                                                                                        
 accounts::users:                                                                                                                            
   test:                                                                                                                                
     managehome: true                                                                                                                        
     comment: "Test user"                                                                                                         
     groups: ["sudo", "plugdev", "admins", "docker"] 
```

                                                   
                              
I then expect puppet to add the test user to the group docker when running puppet. 

What happens, nothing. 

Using version 1.5.3
