### ISSUE TITLE
Users not being assigned to groups as specified in heira

### ISSUE THREAD

**Issue by jamierasmussen** [deric/puppet-accounts#94]
Users are created as expected, however any groups added to the array are ignored.  Appears to  silently fail, with no errors logged.

Example hiera:

```
accounts::users:
  john:
    comment: "John Doe"
    groups:
      - "wheel"
      - "users"
```

I've tried formatting as above, as well as:  `groups: ["wheel", "users"]`
